# Generated by Django 4.2.2 on 2024-02-21 18:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hotel name')),
                ('location', models.CharField(max_length=150, verbose_name='Hotel location')),
                ('google_map', models.CharField(max_length=150, verbose_name='Google map link')),
                ('brief_info', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='hotel_photos', verbose_name='Hotel photo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_photo', to='main.hotel')),
            ],
        ),
    ]
